|Portal| 2025-01-05 17:35:57 [..] Loaded.
|Portal| 2025-01-05 17:35:55 [..] Loading E:\Documents\Development\west_of_doom\.evenv\Lib\site-packages\evennia\server\portal\portal.py...
|Portal| 2025-01-05 17:35:57 [..] Loaded.
|Portal| 2025-01-05 17:35:57 [..] twistd 23.10.0 (E:\Documents\Development\west_of_doom\.evenv\Scripts\python.exe 3.12.8) starting up.
|Portal| 2025-01-05 17:35:57 [..] reactor class: twisted.internet.selectreactor.SelectReactor.
|Portal| 2025-01-05 17:35:58 [..] AMP starting on 4006
|Portal| 2025-01-05 17:35:58 [..] Telnet starting on 4000
|Portal| 2025-01-05 17:35:58 [..] Websocket starting on 4002
|Portal| 2025-01-05 17:35:58 [..] Webserver-proxy starting on 4001
|Portal| 2025-01-05 17:35:58 [..] Portal starting server ... 
|Portal| 2025-01-05 17:41:34 [..] Portal starting server ... 
|Portal| 2025-01-05 18:35:01 [..] Portal starting server ... 
|Portal| 2025-01-05 18:35:46 [..] Portal starting server ... 
|Portal| 2025-01-05 18:36:46 [..] Portal starting server ... 
|Portal| 2025-01-05 18:39:32 [..] Portal starting server ... 
|Portal| 2025-01-05 18:40:23 [..] Portal starting server ... 
|Portal| 2025-01-05 18:46:30 [..] Portal starting server ... 
|Portal| 2025-01-05 18:46:32 [EE] AMP Error from AdminPortal2Server: Traceback (most recent call last):
|Portal| 2025-01-05 18:46:32 [EE] --- <exception caught here> ---
|Portal| 2025-01-05 18:46:32 [EE]   File "E:\Documents\Development\west_of_doom\.evenv\Lib\site-packages\twisted\internet\defer.py", line 1075, in _runCallbacks
|Portal| 2025-01-05 18:46:32 [EE]     current.result = callback(  # type: ignore[misc]
|Portal| 2025-01-05 18:46:32 [EE]   File "E:\Documents\Development\west_of_doom\.evenv\Lib\site-packages\twisted\protocols\amp.py", line 1949, in _massageError
|Portal| 2025-01-05 18:46:32 [EE]     error.trap(RemoteAmpError)
|Portal| 2025-01-05 18:46:32 [EE]   File "E:\Documents\Development\west_of_doom\.evenv\Lib\site-packages\twisted\python\failure.py", line 481, in trap
|Portal| 2025-01-05 18:46:32 [EE]     self.raiseException()
|Portal| 2025-01-05 18:46:32 [EE]   File "E:\Documents\Development\west_of_doom\.evenv\Lib\site-packages\twisted\python\failure.py", line 505, in raiseException
|Portal| 2025-01-05 18:46:32 [EE]     raise self.value.with_traceback(self.tb)
|Portal| 2025-01-05 18:46:32 [EE] twisted.protocols.amp.UnhandledCommand: (b'UNHANDLED', "Unhandled Command: b'AdminPortal2Server'")
|Portal| 2025-01-05 18:46:32 [EE]  (b'UNHANDLED', "Unhandled Command: b'AdminPortal2Server'")
|Portal| 2025-01-05 18:48:21 [..] Portal starting server ... 
|Portal| 2025-01-05 18:54:06 [..] Portal starting server ... 
|Portal| 2025-01-05 18:58:11 [..] (TCP Port 4002 Closed)
|Portal| 2025-01-05 18:58:11 [..] (TCP Port 4000 Closed)
|Portal| 2025-01-05 18:58:11 [..] (TCP Port 4001 Closed)
|Portal| 2025-01-05 18:58:11 [..] (TCP Port 4006 Closed)
|Portal| 2025-01-05 18:58:11 [..] Main loop terminated.
|Portal| 2025-01-05 18:58:11 [..] Server Shut Down.
|Portal| 2025-01-05 18:58:11 [..] Server Shut Down.
